name: Bump formulae on schedule or request

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/autobump.yml
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  schedule:
    # Every 3 hours from 1 through 23 with an offset of 45 minutes
    - cron: "45 1-23/3 * * *"

permissions:
  contents: read

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump:
    if: github.repository_owner == 'huncrys'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: false
          cask: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Get packages to bump
        id: autobump
        run: |
          formulae=$(brew tap-info huncrys/tap --json | jq -r '.[].formula_names | join(" ")')
          casks=$(brew tap-info huncrys/tap --json | jq -r '.[].cask_tokens | join(" ")')
          echo "formulae=$formulae" >> "$GITHUB_OUTPUT"
          echo "casks=$casks" >> "$GITHUB_OUTPUT"

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        continue-on-error: true
        with:
          token: ${{ secrets.TOKEN }}
          formulae: ${{ github.event.inputs.formulae || steps.autobump.outputs.formulae }}
          casks: ${{ github.event.inputs.casks || steps.autobump.outputs.casks }}
          fork: false
